### PR TITLE
Fix alert spam for high message frequency on ws

### LINKED ISSUE #951: WebSocket player spams repeated alerts
**Description**

Lichtblick 1.23.1

When connected to a high-frequency websocket stream, the websocket player repeatedly emits the same warning/error alerts, causing excessive console/log output and eventual debug window instability/crash after some thousands of warnings.

Image

The duplicate alerts don't surface in the UI in production build because they all have the same ID and get deduped at some point, but it probably still causes a bit of performance degradation.

packages/suite-base/src/players/utils/isTopicHighFrequency.ts

**Steps To Reproduce**
1. Connect to a websocket that sends with a frequency higher than 60Hz.
2. Run Lichtblick in debug mode
3. See the debugging console crash after a few thousands of log messages

**Expected Behavior**
I would expect Lichtblick to emit the alert only once when the websocket source exceeds 60Hz.

### PR DESCRIPTION
**Pull request by ctw-joao-luis**
## User-Facing Changes

Fixed an alert spam issue in the WebSocket player where high message frequency warnings were triggered repeatedly. The alert now fires only once per connection session.

This fixes #951 

## Description

The `FoxgloveWebSocketPlayer` was not tracking whether a high-frequency topic had already been detected, causing the alert to be re-evaluated and re-added on every incoming message. This PR fixes that and also refactors the shared high-frequency detection utility to be cleaner and usable by both players.

Changes:

- Added `ishighFrequencyMessage` class field (reset on reconnection in the "open" handler) to ensure `isTopicHighFrequency` is only called until a high-frequency topic is detected. The alert is now added inline, removing the need for the `checkForHighFrequencyTopics` wrapper.

- `isTopicHighFrequency`: removed unused `alerts`, `connectionType`, `startTime`, and `endTime` parameters. The function now takes only `{ topicStats, topic, duration }`, making it usable directly from both `FoxgloveWebSocketPlayer` and `IterablePlayer` without extra coupling;
- `helpers.ts`: Deleted `checkForHighFrequencyTopics` wrapper function;
- `types.ts`: Deleted `CheckForHighFrequencyTopics` type and its orphaned imports;
- `IterablePlayer`: Updated call site to the new `isTopicHighFrequency` signature;
- Tests updated across `isTopicHighFrequency.test.ts` and `helpers.test.ts`.

## How to test it

Created this repo that can be used to test it: https://github.com/ctw-joao-luis/lichtblick-high-frequency-ws 

## Checklist

- [ ] The web version was tested and it is running ok
- [ ] The desktop version was tested and it is running ok
- [ ] This change is covered by unit tests
- [ ] Files constants.ts, types.ts and *.style.ts have been checked and relevant code snippets have been relocated

### CODE REVIEW

File: packages/suite-base/src/players/utils/isTopicHighFrequency.ts [hunk 1]
```diff
@@ -11,33 +10,37 @@ function isLogSchema(schemaName?: string): boolean {
...
+export function isTopicHighFrequency({
+  topicStats,
+  topic,
+  duration,
+}: {
+  topicStats: Map<string, TopicStats>;
+  topic: TopicFrequencyInfo;
+  duration: Time | undefined;
+}): boolean {
+  if (!duration) {
```
Comment (luluiz) [inline packages/suite-base/src/players/utils/isTopicHighFrequency.ts:23]: add unit test when there is no duration

Comment (ctw-joao-luis) [reply packages/suite-base/src/players/utils/isTopicHighFrequency.ts:23]: done
